name: Tests

on: [push]
env:
 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 STATA_LICENSE: ${{ secrets.STATA_LICENSE }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run test suite
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: ./test.sh
